export const ErrorCodes = {
  VALIDATION_ERROR: "VALIDATION_ERROR",
  NOT_FOUND: "NOT_FOUND",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  CONFLICT: "CONFLICT",
  RATE_LIMIT: "RATE_LIMIT",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  AI_NOT_CONFIGURED: "AI_NOT_CONFIGURED",
  AI_UNAVAILABLE: "AI_UNAVAILABLE",
  AI_TIMEOUT: "AI_TIMEOUT",
  AI_INVALID_RESPONSE: "AI_INVALID_RESPONSE",
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
