import {
  TesterProfileInputSchema,
  type TesterProfileInput,
} from '@repo/api-contracts';

const profiles: TesterProfileInput[] = [
  {
    displayName: 'Maja Nowak',
    city: 'Kraków',
    bio: 'Poruszam się na wózku. Chętnie sprawdzę dostępność miejsc, aplikacji i rozwiązań ułatwiających codzienną samodzielność.',
    skills: ['Testowanie dostępności', 'Dokładny opis barier'],
    resources: ['Wózek aktywny', 'Smartfon Android'],
    accessibilityNeeds:
      'Potrzebuję wejścia bez schodów i dostosowanej toalety.',
    interests: ['Dostępność miasta', 'Samodzielność'],
    availability: 'hybrid',
  },
  {
    displayName: 'Kamil Zieliński',
    city: 'Warszawa',
    bio: 'Mam wydajny komputer do grafiki 3D i obliczeń. Mogę sprawdzać prototypy aplikacji, narzędzia AI i wymagające symulacje.',
    skills: ['Testy wydajności', 'Python', 'Grafika 3D'],
    resources: [
      'Komputer stacjonarny RTX 4090',
      '64 GB RAM',
      'Internet światłowodowy',
    ],
    accessibilityNeeds: '',
    interests: ['Technologie społeczne', 'AI', 'Edukacja'],
    availability: 'remote',
  },
  {
    displayName: 'Anna Wójcik',
    city: 'Gdańsk',
    bio: 'Jestem osobą niewidomą i korzystam z czytnika ekranu. Mogę testować aplikacje i materiały edukacyjne obsługiwane bez wzroku.',
    skills: ['Testy z czytnikiem ekranu', 'Ocena dostępności dokumentów'],
    resources: ['iPhone z VoiceOver', 'Laptop z NVDA'],
    accessibilityNeeds:
      'Potrzebuję materiałów dostępnych dla czytnika ekranu i tekstowych opisów grafiki.',
    interests: ['Edukacja', 'Dostępne usługi cyfrowe'],
    availability: 'remote',
  },
  {
    displayName: 'Piotr Wiśniewski',
    city: 'Wrocław',
    bio: 'Jestem osobą słabosłyszącą. Chętnie sprawdzę napisy, komunikację tekstową i rozwiązania wspierające udział w wydarzeniach.',
    skills: ['Ocena napisów', 'Testowanie aplikacji komunikacyjnych'],
    resources: ['Smartfon Android', 'Laptop'],
    accessibilityNeeds:
      'Preferuję kontakt tekstowy i napisy podczas spotkań online.',
    interests: ['Kultura dostępna', 'Komunikacja'],
    availability: 'hybrid',
  },
  {
    displayName: 'Ewa Kamińska',
    city: 'Łódź',
    bio: 'Mam 68 lat. Korzystam ze smartfona i chcę sprawdzać, czy nowe usługi są zrozumiałe dla seniorów zaczynających przygodę z technologią.',
    skills: ['Ocena prostoty obsługi', 'Organizacja spotkań sąsiedzkich'],
    resources: ['Smartfon Android', 'Tablet'],
    accessibilityNeeds:
      'Wygodniej czytam duży tekst i instrukcje pisane prostym językiem.',
    interests: ['Relacje sąsiedzkie', 'Usługi dla seniorów'],
    availability: 'hybrid',
  },
  {
    displayName: 'Tomasz Lewandowski',
    city: 'Poznań',
    bio: 'Jestem rodzicem dwójki dzieci i prowadzę warsztaty w lokalnej świetlicy. Mogę testować narzędzia pomagające rodzicom i edukatorom.',
    skills: ['Prowadzenie warsztatów', 'Planowanie zajęć'],
    resources: ['Projektor', 'Laptop', 'Sala warsztatowa po uzgodnieniu'],
    accessibilityNeeds: '',
    interests: ['Wsparcie rodzin', 'Edukacja dzieci'],
    availability: 'onsite',
  },
  {
    displayName: 'Oliwia Mazur',
    city: 'Katowice',
    bio: 'Tworzę interaktywne materiały edukacyjne. Posiadam gogle VR i kontrolery, które mogę wykorzystać do testów prototypów społecznych.',
    skills: ['Testowanie VR', 'Projektowanie zajęć'],
    resources: ['Gogle Meta Quest 3', 'Kontrolery VR', 'Laptop do grafiki'],
    accessibilityNeeds: '',
    interests: ['Wirtualna rzeczywistość', 'Edukacja', 'Integracja społeczna'],
    availability: 'hybrid',
  },
  {
    displayName: 'Jakub Dąbrowski',
    city: 'Nowy Sącz',
    bio: 'Mieszkam poza centrum i działam w lokalnej grupie wolontariackiej. Chętnie sprawdzę rozwiązania ułatwiające transport i dostęp do usług na wsi.',
    skills: ['Koordynacja wolontariatu', 'Testy w terenie'],
    resources: ['Rower elektryczny', 'Smartfon Android'],
    accessibilityNeeds: '',
    interests: [
      'Transport lokalny',
      'Wolontariat',
      'Usługi na obszarach wiejskich',
    ],
    availability: 'onsite',
  },
  {
    displayName: 'Zofia Lis',
    city: 'Lublin',
    bio: 'Pracuję z polskim i ukraińskim tekstem. Pomagam oceniać, czy komunikaty dla osób przyjeżdżających do Polski są zrozumiałe i użyteczne.',
    skills: ['Język polski', 'Język ukraiński', 'Redakcja prostego języka'],
    resources: ['Laptop', 'Smartfon'],
    accessibilityNeeds: '',
    interests: ['Integracja międzykulturowa', 'Dostęp do informacji'],
    availability: 'remote',
  },
  {
    displayName: 'Michał Król',
    city: 'Kraków',
    bio: 'Jestem testerem oprogramowania. Sprawdzam obsługę klawiaturą i kontrast interfejsów oraz pomagam opisywać błędy w prototypach.',
    skills: ['Testy manualne', 'Dostępność WCAG', 'Raportowanie błędów'],
    resources: ['Laptop Windows', 'Telefon iOS', 'Telefon Android'],
    accessibilityNeeds: '',
    interests: ['Dostępność cyfrowa', 'Otwarte technologie'],
    availability: 'remote',
  },
];

type SeedGroup = Omit<TesterProfileInput, 'displayName' | 'city' | 'bio'> & {
  people: [name: string, city: string, bio: string, resource: string][];
};

// Fictional profiles only. Preserve the order: seed owner hashes use these indexes.
const groups: SeedGroup[] = [
  {
    skills: ['Pomiary środowiskowe', 'Dokumentacja testów'],
    resources: ['Smartfon Android'],
    accessibilityNeeds: '',
    interests: ['Czujniki', 'Jakość powietrza', 'Nauka obywatelska'],
    availability: 'hybrid',
    people: [
      ['Natalia Borkowska', 'Rybnik', 'Porównuję odczyty pyłu przy ruchliwej ulicy i w podwórzu. Sprawdzę nowy czujnik smogu oraz czytelność jego alarmów.', 'Czujnik pyłu PM2.5'],
      ['Marcin Wrona', 'Tarnów', 'Prowadzę dziennik temperatury w mieszkaniu na poddaszu. Mogę przez miesiąc porównywać prototyp z domowym termometrem.', 'Rejestrator temperatury'],
      ['Agata Sadowska', 'Opole', 'Wspieram ogród społeczny i zapisuję wilgotność gleby po podlewaniu. Przetestuję czujnik oszczędzający wodę.', 'Wilgotnościomierz gleby'],
      ['Bartosz Cieślak', 'Bielsko-Biała', 'Lutuję proste układy pomiarowe. Chcę sprawdzić obudowę i zasilanie terenowego czujnika zalania piwnicy.', 'ESP32 i stacja lutownicza'],
      ['Karolina Gajda', 'Płock', 'Mieszkam przy głośnym skrzyżowaniu. Mogę porównywać mapę hałasu z pomiarami w stałych porach dnia.', 'Miernik poziomu dźwięku'],
      ['Łukasz Pietrzak', 'Słupsk', 'Opiekuję się szkolnym akwarium i notuję parametry wody. Ocenię prostą instrukcję podłączenia nowego sensora.', 'Zestaw pomiaru pH'],
      ['Monika Wolska', 'Kielce', 'Sprawdzam wietrzenie sali spotkań sąsiedzkich. Interesuje mnie czujnik CO2 z komunikatem zrozumiałym bez wykresów.', 'Miernik CO2'],
      ['Paweł Górski', 'Suwałki', 'Zapisuję pogodę przy domu i znam problemy baterii na mrozie. Mogę przeprowadzać regularne testy czujnika na zewnątrz.', 'Domowa stacja pogodowa'],
      ['Aleksandra Sobczak', 'Zamość', 'Zajmuję się szklarnią na działce. Sprawdzę powiadomienia o przymrozku i zbyt wysokiej temperaturze.', 'Szklarnia i termometr minimalny'],
      ['Rafał Kubiak', 'Konin', 'Mierzę zużycie prądu domowych urządzeń. Chętnie ocenię czujnik, który wyjaśnia wyniki bez technicznego słownictwa.', 'Watomierz gniazdkowy'],
    ],
  },
  {
    skills: ['Testy wydajności', 'Raportowanie błędów'],
    resources: ['Internet światłowodowy'],
    accessibilityNeeds: '',
    interests: ['Mocny komputer', 'Otwarte oprogramowanie', 'AI'],
    availability: 'remote',
    people: [
      ['Dominik Kaczmarek', 'Warszawa', 'Renderuję modele budynków i mierzę czas obliczeń. Udostępnię wieczory na testy aplikacji wymagającej mocnego GPU.', 'Komputer RTX 4080 i 64 GB RAM'],
      ['Justyna Pawlak', 'Poznań', 'Montuję długie nagrania warsztatów. Sprawdzę generowanie napisów i stabilność narzędzia przy dużych plikach.', 'Stacja robocza RTX 4070 i 32 GB RAM'],
      ['Adrian Sokołowski', 'Wrocław', 'Uruchamiam modele językowe lokalnie. Mogę porównać zużycie pamięci i responsywność prototypu asystenta społecznego.', 'Komputer RTX 4090 i 128 GB RAM'],
      ['Weronika Michalska', 'Gdynia', 'Przygotowuję wizualizacje danych miejskich. Interesują mnie testy dużych zbiorów na komputerze z systemem Linux.', 'Linux i procesor Ryzen 9'],
      ['Filip Jankowski', 'Kraków', 'Tworzę animacje edukacyjne i sceny 3D. Ocenię płynność interaktywnej lekcji na wysokich ustawieniach grafiki.', 'Komputer Radeon RX 7900 XTX'],
      ['Paulina Zawadzka', 'Łódź', 'Analizuję otwarte dane w Pythonie. Mogę sprawdzać import plików i powtarzalność obliczeń w nowym narzędziu badawczym.', 'Komputer 96 GB RAM i dysk NVMe 4 TB'],
      ['Szymon Brzeziński', 'Gliwice', 'Buduję symulacje ruchu pieszych. Chcę testować rozwiązania planowania bezpiecznych dojść do szkół.', 'Stacja robocza 24 rdzenie i 64 GB RAM'],
      ['Martyna Dudek', 'Szczecin', 'Prowadzę transmisje spotkań fundacji. Mogę ocenić jednoczesne tłumaczenie, napisy i obciążenie aplikacji.', 'Komputer RTX 4060 Ti i kamera USB'],
      ['Krzysztof Baran', 'Rzeszów', 'Składam komputery i porównuję konfiguracje sprzętu. Zapiszę temperatury oraz pobór energii podczas długiego testu.', 'Komputer RTX 3080 i monitor 4K'],
      ['Julia Sikora', 'Olsztyn', 'Pracuję z dużymi zdjęciami map i ortofotomap. Sprawdzę narzędzie wykrywające bariery terenowe na obrazach.', 'Mac Studio i 64 GB pamięci'],
    ],
  },
  {
    skills: ['Ocena dostępności przestrzeni', 'Opis barier ruchowych'],
    resources: ['Smartfon'],
    accessibilityNeeds: 'Potrzebuję bezstopniowego wejścia, odpowiednio szerokiego przejścia i dostępnej toalety.',
    interests: ['Samodzielność', 'Dostępny transport', 'Projektowanie uniwersalne'],
    availability: 'hybrid',
    people: [
      ['Marta Malinowska', 'Gdańsk', 'Poruszam się na wózku aktywnym i dojeżdżam do pracy tramwajem. Sprawdzę mapę przesiadek oraz informacje o windach.', 'Wózek aktywny'],
      ['Wojciech Kołodziej', 'Lublin', 'Korzystam z wózka elektrycznego. Mogę oceniać promień skrętu, dostęp do przycisków i oznaczenie tras w budynkach.', 'Wózek elektryczny'],
      ['Beata Marciniak', 'Toruń', 'Na co dzień chodzę z balkonikiem. Zwracam uwagę na miejsca odpoczynku i czas potrzebny na przejście przez ulicę.', 'Balkonik czterokołowy'],
      ['Dawid Olszewski', 'Bydgoszcz', 'Używam kul i często korzystam z pociągów. Ocenię zamawianie asysty oraz informacje o wysokości stopni.', 'Kule łokciowe'],
      ['Renata Nowicka', 'Radom', 'Poruszam się na wózku i prowadzę sklep internetowy. Interesują mnie dostępne paczkomaty i samodzielny odbiór przesyłek.', 'Wózek manualny i laptop'],
      ['Grzegorz Zalewski', 'Elbląg', 'Mam ograniczoną sprawność dłoni. Sprawdzę duże przyciski, uchwyty i aplikacje niewymagające precyzyjnych gestów.', 'Mysz z dużym trackballem'],
      ['Iwona Urbańska', 'Kalisz', 'Korzystam ze skutera wspomagającego mobilność. Mogę testować trasy do biblioteki i dostępne punkty ładowania.', 'Skuter mobilny'],
      ['Maciej Ostrowski', 'Siedlce', 'Jako użytkownik wózka odwiedzam lokalne wydarzenia. Sprawdzę rezerwację miejsc i rzeczywiste dojście do sceny.', 'Wózek aktywny i aparat'],
      ['Dorota Jabłońska', 'Legnica', 'Po schodach poruszam się powoli z laską. Mogę ocenić plan budynku i informację o alternatywnym wejściu.', 'Laska podpierająca'],
      ['Artur Szczepański', 'Koszalin', 'Prowadzę sportowe zajęcia integracyjne i korzystam z wózka. Sprawdzę dostęp do szatni oraz wypożyczanie sprzętu.', 'Wózek sportowy'],
    ],
  },
  {
    skills: ['Testy bez użycia wzroku', 'Obsługa klawiatury'],
    resources: ['Laptop'],
    accessibilityNeeds: 'Potrzebuję opisów tekstowych, logicznych nagłówków i formularzy współpracujących z czytnikiem ekranu.',
    interests: ['Dostępność cyfrowa', 'Samodzielne załatwianie spraw'],
    availability: 'remote',
    people: [
      ['Joanna Krawczyk', 'Warszawa', 'Jestem niewidoma i czytam książki w formacie cyfrowym. Sprawdzę wyszukiwanie tytułów oraz wypożyczanie bez myszy.', 'NVDA i klawiatura brajlowska'],
      ['Mateusz Piotrowski', 'Kraków', 'Korzystam z VoiceOver w telefonie. Mogę przetestować instrukcję parowania czujnika i odczyt jego powiadomień.', 'iPhone z VoiceOver'],
      ['Elżbieta Grabowska', 'Poznań', 'Mam słaby wzrok i powiększam ekran. Ocenię rezerwację wizyty przy dużej czcionce i bez poziomego przewijania.', 'Monitor 32 cale i lupa ekranowa'],
      ['Sebastian Nowicki', 'Gdańsk', 'Obsługuję komputer czytnikiem JAWS. Chętnie sprawdzę tabele wyników, etykiety formularzy i pobieranie dokumentów.', 'Windows z JAWS'],
      ['Alicja Wróbel', 'Wrocław', 'Korzystam z TalkBack podczas codziennych podróży. Sprawdzę komunikaty aplikacji o zmianie przystanku i opóźnieniach.', 'Android z TalkBack'],
      ['Robert Majewski', 'Łódź', 'Mam ograniczone pole widzenia. Ocenię wyszukiwanie ważnych komunikatów oraz układ krótkich formularzy.', 'Tablet z powiększeniem ekranu'],
      ['Magdalena Olszewska', 'Lublin', 'Jestem niewidoma i pracuję z tekstem. Mogę porównać dostępność formularza kontaktu w kilku przeglądarkach.', 'NVDA i Firefox'],
      ['Przemysław Kurek', 'Opole', 'Korzystam z brajlowskiej linijki i uczę się programowania. Chcę testować interaktywne ćwiczenia edukacyjne.', 'Monitor brajlowski'],
      ['Teresa Wysocka', 'Białystok', 'Czytam przy dużym powiększeniu i wysokim kontraście. Sprawdzę czytelność ostrzeżeń i stanów przycisków.', 'Lupa elektroniczna'],
      ['Mikołaj Stępień', 'Tychy', 'Używam syntezy mowy i skrótów klawiaturowych. Sprawdzę, czy interfejs daje się obsłużyć w logicznej kolejności.', 'Linux z Orca'],
    ],
  },
  {
    skills: ['Ocena komunikacji wizualnej', 'Testowanie napisów'],
    resources: ['Smartfon i laptop'],
    accessibilityNeeds: 'Proszę o kontakt tekstowy, napisy do nagrań i wizualny odpowiednik alarmów dźwiękowych.',
    interests: ['Dostępna komunikacja', 'Kultura', 'Powiadomienia'],
    availability: 'hybrid',
    people: [
      ['Patrycja Czerwińska', 'Kraków', 'Jestem osobą Głuchą i używam PJM. Ocenię widoczność tłumacza w wideorozmowie oraz kolejność komunikatów tekstowych.', 'Monitor 27 cali'],
      ['Daniel Wesołowski', 'Warszawa', 'Słabo słyszę i korzystam z aparatów słuchowych. Sprawdzę jakość napisów podczas spotkań z kilkoma osobami.', 'Aparaty słuchowe z Bluetooth'],
      ['Kinga Błaszczyk', 'Poznań', 'Nie słyszę alarmów domowych. Chętnie sprawdzę lampkę lub opaskę wibrującą po sygnale z nowego czujnika.', 'Opaska z wibracjami'],
      ['Marek Sawicki', 'Szczecin', 'Pracuję w hałaśliwym warsztacie i mam ubytek słuchu. Ocenię czytelność ostrzeżeń świetlnych i komunikatów aplikacji.', 'Smartwatch'],
      ['Sylwia Szymczak', 'Gdynia', 'Oglądam wydarzenia z napisami. Mogę zgłaszać opóźnienia, brak oznaczenia mówcy i zbyt szybko znikające linie.', 'Tablet 11 cali'],
      ['Adam Lisowski', 'Katowice', 'Korzystam głównie z wiadomości tekstowych. Sprawdzę rejestrację do usług bez obowiązku wykonania telefonu.', 'Telefon Android'],
      ['Wiktoria Chmielewska', 'Rzeszów', 'Jestem osobą słabosłyszącą i prowadzę klub filmowy. Ocenię napisy oraz dostępne opisy wydarzeń kulturalnych.', 'Projektor'],
      ['Jacek Duda', 'Olsztyn', 'Noszę aparat słuchowy i podróżuję koleją. Sprawdzę tekstowe powiadomienia o zmianach peronu i opóźnieniach.', 'iPhone'],
      ['Lucyna Kaczor', 'Gorzów Wielkopolski', 'W komunikacji używam PJM i polskiego tekstu. Pomogę ocenić proste instrukcje wideo z tłumaczeniem migowym.', 'Kamera internetowa'],
      ['Marcel Krupa', 'Bielsko-Biała', 'Jestem niesłyszący i jeżdżę rowerem. Interesują mnie wibracyjne sygnały nawigacji bez patrzenia na mapę.', 'Uchwyt rowerowy na telefon'],
    ],
  },
  {
    skills: ['Ocena użyteczności', 'Dzielenie się doświadczeniem'],
    resources: ['Smartfon'],
    accessibilityNeeds: 'Preferuję czytelny tekst oraz możliwość spokojnego powtórzenia instrukcji.',
    interests: ['Aktywność seniorów', 'Relacje sąsiedzkie', 'Samodzielność'],
    availability: 'hybrid',
    people: [
      ['Halina Pawłowska', 'Sandomierz', 'Mam 72 lata i koordynuję klub czytelniczy. Sprawdzę zapisy na spotkania oraz łatwe przypomnienia o terminie.', 'Tablet Android'],
      ['Stanisław Walczak', 'Piła', 'Mam 69 lat i sam konfiguruję domową sieć. Chcę testować czujniki ostrzegające o pozostawionym otwartym oknie.', 'Domowa sieć Wi-Fi'],
      ['Bożena Michalak', 'Leszno', 'Mam 76 lat, a smartfona używam od roku. Ocenię pierwszy kontakt z aplikacją do umawiania transportu.', 'Smartfon z dużym ekranem'],
      ['Henryk Tomaszewski', 'Przemyśl', 'Mam 81 lat i piszę kronikę osiedla. Mogę sprawdzić dyktowanie wspomnień i poprawianie automatycznego zapisu.', 'Laptop i mikrofon'],
      ['Krystyna Włodarczyk', 'Puławy', 'Mam 67 lat i uczę sąsiadów wideorozmów. Sprawdzę instrukcje, które pomagają wrócić do przerwanej czynności.', 'Laptop Windows'],
      ['Zbigniew Nowakowski', 'Ostrołęka', 'Mam 74 lata i jeżdżę na wycieczki rowerowe. Interesuje mnie prosty plan trasy z miejscami odpoczynku.', 'Rower trekkingowy'],
      ['Danuta Piotrowska', 'Ełk', 'Mam 70 lat i działam w kole rękodzieła. Ocenię zamieszczanie zdjęć prac bez skomplikowanych ustawień konta.', 'Aparat kompaktowy'],
      ['Janusz Kwiatkowski', 'Świdnica', 'Mam 78 lat i korzystam z bankowości internetowej. Sprawdzę zrozumiałość komunikatów potwierdzających ważne działania.', 'Komputer stacjonarny'],
      ['Wanda Zając', 'Kołobrzeg', 'Mam 83 lata i częściej używam telefonu niż komputera. Chętnie ocenię prosty kalendarz wizyt i spotkań.', 'Telefon iOS'],
      ['Ryszard Kaczmarczyk', 'Chojnice', 'Mam 66 lat i prowadzę grupę spacerową. Sprawdzę ogłoszenia sąsiedzkie oraz zgłaszanie chęci udziału.', 'Zegarek z krokomierzem'],
    ],
  },
  {
    skills: ['Ocena prostego języka', 'Test pierwszego użycia'],
    resources: ['Telefon Android'],
    accessibilityNeeds: 'Pomagają mi krótkie kroki, przykłady i brak pośpiechu podczas wykonywania zadania.',
    interests: ['Kompetencje cyfrowe', 'Proste formularze', 'Dostęp do usług'],
    availability: 'onsite',
    people: [
      ['Aneta Kozłowska', 'Mława', 'Mam 42 lata i rzadko korzystam z komputera. Mogę opisać miejsca, w których gubię się podczas rejestracji do usługi.', 'Pożyczany laptop'],
      ['Mariusz Wieczorek', 'Żary', 'Na co dzień używam telefonu do rozmów i zdjęć. Sprawdzę, czy da się wysłać zgłoszenie bez znajomości technicznych pojęć.', 'Telefon z małą pamięcią'],
      ['Edyta Adamczyk', 'Kętrzyn', 'Wracam do nauki obsługi internetu po długiej przerwie. Chcę sprawdzić instrukcje odzyskiwania dostępu do konta.', 'Tablet rodzinny'],
      ['Dariusz Jaworski', 'Kraśnik', 'Pracuję fizycznie i nie piszę szybko na klawiaturze. Ocenię formularz, który można wypełnić krótkimi odpowiedziami.', 'Starszy laptop'],
      ['Izabela Sroka', 'Wieluń', 'Korzystam z internetu tylko w telefonie. Sprawdzę przesyłanie zdjęcia i rozpoznanie, czy formularz został już wysłany.', 'Telefon z ekranem 5 cali'],
      ['Waldemar Mazurek', 'Łuków', 'Dotąd sprawy urzędowe załatwiałem osobiście. Chętnie przejdę krok po kroku przez nową usługę cyfrową.', 'Komputer biblioteczny po uzgodnieniu'],
      ['Grażyna Bielecka', 'Wągrowiec', 'Mam trudność z rozpoznawaniem ikon bez podpisu. Mogę ocenić menu oraz nazwy przycisków w prototypie.', 'Smartfon z powiększoną czcionką'],
      ['Cezary Kłos', 'Bartoszyce', 'Uczę się korzystania z poczty i załączników. Sprawdzę, czy instrukcja pozwala samodzielnie dodać dokument.', 'Laptop z Windows 11'],
      ['Lidia Wawrzyniak', 'Biłgoraj', 'Internet w domu bywa niestabilny i korzystam głównie z pakietu komórkowego. Ocenię prostotę obsługi po utracie połączenia.', 'Mobilny internet LTE'],
      ['Leszek Czarnecki', 'Pszczyna', 'Mam 55 lat i zaczynam używać aplikacji mobilnych. Zapiszę pytania pojawiające się podczas pierwszego logowania.', 'Telefon Android Go'],
    ],
  },
  {
    skills: ['Planowanie codziennych obowiązków', 'Ocena usług dla rodzin'],
    resources: ['Smartfon'],
    accessibilityNeeds: '',
    interests: ['Wsparcie opiekunów', 'Rodzina', 'Organizacja czasu'],
    availability: 'remote',
    people: [
      ['Barbara Rutkowska', 'Łódź', 'Łączę pracę z opieką nad tatą. Sprawdzę współdzielony kalendarz dyżurów, który nie wymaga długiej konfiguracji.', 'Tablet do wideorozmów'],
      ['Konrad Witkowski', 'Gdańsk', 'Jestem ojcem bliźniąt i organizuję wymianę ubrań. Chcę ocenić rezerwację przedmiotów i jasne zasady odbioru.', 'Laptop'],
      ['Joanna Cieślak', 'Poznań', 'Opiekuję się bliską osobą o ograniczonej mobilności. Mogę testować wyszukiwanie dostępnego transportu na konkretną godzinę.', 'Samochód osobowy'],
      ['Damian Wójcicki', 'Kraków', 'Dzielę obowiązki rodzicielskie pomiędzy dwa domy. Sprawdzę prostą listę rzeczy do przekazania i powiadomienia o zmianach.', 'Telefon iOS'],
      ['Agnieszka Głowacka', 'Lublin', 'Pomagam mamie w zakupach i codziennych sprawach. Ocenię sąsiedzką listę potrzeb z możliwością potwierdzenia realizacji.', 'Laptop Chromebook'],
      ['Piotr Szymkowiak', 'Toruń', 'Prowadzę dom i pracuję zmianowo. Interesuje mnie koordynowanie odbioru dzieci bez wielokrotnego wysyłania wiadomości.', 'Kalendarz współdzielony'],
      ['Katarzyna Witek', 'Rzeszów', 'Jako opiekunka rodzinna korzystam z krótkich przerw w ciągu dnia. Sprawdzę formularze, które zachowują niedokończoną pracę.', 'Smartfon Android'],
      ['Andrzej Zawadzki', 'Olsztyn', 'Pomagam starszemu sąsiadowi w dojazdach. Mogę ocenić zgłaszanie prośby o transport i czytelne potwierdzenie terminu.', 'Samochód kombi'],
      ['Magdalena Kania', 'Kielce', 'Organizuję grupę wzajemnego wsparcia rodziców. Chętnie przetestuję anonimową skrzynkę pytań i harmonogram spotkań.', 'Kamera internetowa'],
      ['Tadeusz Cieślar', 'Bielsko-Biała', 'Wspieram dorosłego syna w planowaniu tygodnia. Sprawdzę wizualny harmonogram z prostymi powtarzalnymi czynnościami.', 'Tablet 10 cali'],
    ],
  },
  {
    skills: ['Prowadzenie zajęć', 'Zbieranie informacji zwrotnej'],
    resources: ['Laptop'],
    accessibilityNeeds: '',
    interests: ['Edukacja', 'Uczenie przez działanie', 'Materiały dostępne'],
    availability: 'hybrid',
    people: [
      ['Emilia Wierzbicka', 'Wrocław', 'Uczę matematyki dorosłych w małych grupach. Sprawdzę ćwiczenia tłumaczące procenty na codziennych przykładach.', 'Tablet graficzny'],
      ['Hubert Górecki', 'Warszawa', 'Prowadzę otwarte warsztaty elektroniki. Ocenię zestaw do samodzielnego budowania prostego czujnika światła.', 'Zestawy Arduino'],
      ['Olga Michalak', 'Gdynia', 'Pracuję w bibliotece i pomagam wyszukiwać informacje. Chcę testować narzędzie oceny wiarygodności wiadomości.', 'Czytnik e-booków'],
      ['Patryk Sobieski', 'Katowice', 'Uczę fotografii w domu kultury. Sprawdzę krótkie instrukcje zrozumiałe również bez specjalistycznego słownictwa.', 'Aparat bezlusterkowy'],
      ['Kamila Jasińska', 'Zielona Góra', 'Projektuję gry językowe dla dorosłych. Mogę ocenić tempo zadań i informację zwrotną po błędnej odpowiedzi.', 'Drukarka kolorowa'],
      ['Kacper Cichocki', 'Szczecin', 'Prowadzę koło robotyki. Zbadam stabilność połączenia urządzeń i instrukcję pierwszego uruchomienia.', 'Robot edukacyjny'],
      ['Urszula Musiał', 'Białystok', 'Wspieram naukę czytania przez proste teksty. Ocenię podział instrukcji na kroki i przydatność przykładów.', 'Laminator'],
      ['Witold Rogowski', 'Tarnów', 'Tworzę kursy audio do samodzielnej nauki. Sprawdzę odtwarzacz, transkrypcję i zapamiętywanie miejsca odsłuchu.', 'Mikrofon USB'],
      ['Milena Przybylska', 'Opole', 'Prowadzę warsztaty pracy zespołowej. Interesują mnie narzędzia do równomiernego zbierania głosów uczestników.', 'Projektor przenośny'],
      ['Oskar Wilk', 'Nowy Sącz', 'Uczę podstaw programowania w lokalnej świetlicy. Ocenię zadania działające na starszym, mniej wydajnym sprzęcie.', 'Laptop z 4 GB RAM'],
    ],
  },
  {
    skills: ['Testy w terenie', 'Znajomość lokalnych potrzeb'],
    resources: ['Telefon z GPS'],
    accessibilityNeeds: '',
    interests: ['Obszary wiejskie', 'Dostęp do usług', 'Transport lokalny'],
    availability: 'onsite',
    people: [
      ['Celina Bąk', 'Limanowa', 'Mieszkam w przysiółku z rzadkim autobusem. Sprawdzę wspólne planowanie dojazdów do przychodni i sklepu.', 'Samochód osobowy'],
      ['Bogdan Kaczorowski', 'Hajnówka', 'Pomagam organizować dowóz zakupów z miasteczka. Ocenię prostą listę zamówień działającą przy słabym zasięgu.', 'Telefon z internetem 3G'],
      ['Maria Jakubowska', 'Kłodzko', 'Działam w świetlicy wiejskiej. Mogę zbierać uwagi do systemu zapisów na objazdowe usługi biblioteczne.', 'Sala świetlicy po uzgodnieniu'],
      ['Zdzisław Domański', 'Sokółka', 'Znam lokalne drogi gruntowe i dojazdy do przystanków. Sprawdzę mapę tras po większych opadach.', 'Rower trekkingowy'],
      ['Wioletta Kalinowska', 'Bytów', 'Koordynuję koło gospodyń i wydarzenia w kilku wsiach. Interesuje mnie czytelna tablica ogłoszeń dostępna na telefonie.', 'Przenośny router LTE'],
      ['Bronisław Sowa', 'Sanok', 'Mieszkam daleko od urzędu i nie zawsze mam internet. Mogę ocenić przygotowanie sprawy online z możliwością pracy offline.', 'Laptop z modemem'],
      ['Sabina Krajewska', 'Węgrów', 'Prowadzę lokalny punkt wymiany książek. Sprawdzę rezerwację przedmiotu i informację o godzinach odbioru.', 'Mała biblioteczka sąsiedzka'],
      ['Leon Bielecki', 'Giżycko', 'Latem pomagam w informacji turystycznej, zimą wspieram sąsiadów. Sprawdzę sezonowe rozkłady lokalnych połączeń.', 'Tablet z GPS'],
      ['Aniela Bednarek', 'Strzelce Opolskie', 'Organizuję spotkania mieszkańców bez stałego dostępu do komputera. Ocenię zapisy przez krótką wiadomość w telefonie.', 'Telefon z dużą baterią'],
      ['Roman Urban', 'Nysa', 'Pomagam przy sąsiedzkiej wymianie narzędzi. Chcę testować kalendarz wypożyczeń obejmujący kilka okolicznych miejscowości.', 'Przyczepka samochodowa'],
    ],
  },
  {
    skills: ['Porównywanie zużycia zasobów', 'Prowadzenie dziennika obserwacji'],
    resources: ['Arkusz kalkulacyjny'],
    accessibilityNeeds: '',
    interests: ['Oszczędzanie energii', 'Klimat', 'Komfort mieszkania'],
    availability: 'hybrid',
    people: [
      ['Lena Makowska', 'Poznań', 'Porównuję rachunki za ogrzewanie we wspólnocie. Ocenię wykresy pokazujące, które zmiany rzeczywiście ograniczają zużycie.', 'Ciepłomierz z odczytem miesięcznym'],
      ['Norbert Kwiatkowski', 'Gorzów Wielkopolski', 'Mam małą instalację fotowoltaiczną. Sprawdzę proste prognozowanie produkcji i planowanie pracy urządzeń.', 'Instalacja PV 4 kW'],
      ['Nina Dąbrowska', 'Wrocław', 'Mieszkam w nagrzewającym się bloku. Chcę testować powiadomienia o upale i propozycje zacienienia mieszkania.', 'Termometr pokojowy'],
      ['Albert Zieliński', 'Łódź', 'Zapisuję zużycie wody przed i po zmianie perlatorów. Mogę ocenić czujnik nieszczelności w domowej instalacji.', 'Licznik wody z odczytem ręcznym'],
      ['Daria Bieńkowska', 'Toruń', 'Organizuję sąsiedzką wymianę rzeczy zamiast kupowania nowych. Sprawdzę opis stanu przedmiotów i rezerwację odbioru.', 'Aparat w telefonie'],
      ['Ernest Jankowiak', 'Gdańsk', 'Korzystam z inteligentnych gniazdek. Interesuje mnie porównanie sterowania ręcznego i automatycznych harmonogramów.', 'Gniazdka Wi-Fi z pomiarem energii'],
      ['Ilona Markowska', 'Kielce', 'Wspieram lokalną grupę zakupową energii. Ocenię wyjaśnienie taryf i porównanie kosztów napisane prostym językiem.', 'Laptop'],
      ['Błażej Ziółkowski', 'Radom', 'Naprawiam drobne nieszczelności w domu. Chcę testować instrukcję lokalizowania strat ciepła bez specjalistycznej wiedzy.', 'Kamera termowizyjna do telefonu'],
      ['Regina Malinowska', 'Elbląg', 'Prowadzę wspólny ogródek pod blokiem. Sprawdzę planowanie zbierania deszczówki i przypomnienia o podlewaniu.', 'Zbiornik na deszczówkę'],
      ['Eryk Czapla', 'Rybnik', 'Jeżdżę komunikacją miejską i zapisuję jakość powietrza. Ocenię zestawienie emisji i kosztów codziennych podróży.', 'Miernik pyłu przenośny'],
    ],
  },
  {
    skills: ['Ocena tras', 'Dokumentowanie podróży'],
    resources: ['Smartfon z GPS'],
    accessibilityNeeds: '',
    interests: ['Mobilność miejska', 'Bezpieczeństwo', 'Transport publiczny'],
    availability: 'onsite',
    people: [
      ['Sandra Włodarska', 'Warszawa', 'Codziennie łączę metro i autobus. Sprawdzę, czy aplikacja jasno pokazuje czas dojścia między przystankami.', 'Bilet komunikacji miejskiej'],
      ['Dorian Bednarski', 'Kraków', 'Rozwożę zakupy rowerem cargo. Mogę sprawdzać szerokość przejazdów i bezpieczne miejsca krótkiego postoju.', 'Rower cargo'],
      ['Malwina Górska', 'Poznań', 'Chodzę pieszo do pracy i fotografuję niebezpieczne przejścia. Przetestuję zgłaszanie barier na mapie.', 'Aparat kompaktowy'],
      ['Radosław Wysocki', 'Wrocław', 'Korzystam z roweru elektrycznego na długich dojazdach. Ocenię planowanie trasy z uwzględnieniem baterii.', 'Rower elektryczny'],
      ['Karina Kubiak', 'Szczecin', 'Dojeżdżam z przedmieść i czekam na wieczorne autobusy. Sprawdzę powiadomienia o ostatnim połączeniu.', 'Powerbank'],
      ['Igor Michalski', 'Gdańsk', 'Podróżuję koleją z dużym bagażem. Interesuje mnie informacja o windach, schodach i długości przesiadki.', 'Walizka podróżna'],
      ['Natasza Krawiec', 'Łódź', 'Wożę dziecko w wózku i często zmieniam tramwaje. Ocenię oznaczenia pojazdów niskopodłogowych.', 'Wózek dziecięcy'],
      ['Wiktor Grzelak', 'Katowice', 'Testuję trasy rowerowe po zmroku. Sprawdzę mapę oświetlenia i czytelność ostrzeżeń podczas jazdy.', 'Lampka rowerowa i kamera'],
      ['Adrianna Kamińska', 'Lublin', 'Nie mam samochodu i planuję zakupy przy trasie autobusu. Chcę sprawdzić wyszukiwanie usług dostępnych po drodze.', 'Tablet'],
      ['Borys Lewicki', 'Białystok', 'Często przesiadam się między transportem regionalnym i miejskim. Ocenię spójność nazw przystanków i biletów.', 'Telefon Android'],
    ],
  },
  {
    skills: ['Koordynacja wolontariatu', 'Organizacja wydarzeń'],
    resources: ['Laptop i telefon'],
    accessibilityNeeds: '',
    interests: ['Wolontariat', 'Innowacje społeczne', 'Pomoc sąsiedzka'],
    availability: 'hybrid',
    people: [
      ['Zuzanna Brzozowska', 'Kraków', 'Planuję dyżury w jadłodzielni. Sprawdzę zastępstwa i przypomnienia, które nie wymagają instalowania nowej aplikacji.', 'Współdzielony kalendarz'],
      ['Aleksander Włodarczyk', 'Warszawa', 'Koordynuję weekendowe sprzątanie rzeki. Ocenię zapisy uczestników oraz listę dostępnego wyposażenia.', 'Rękawice i chwytaki do odpadów'],
      ['Iga Pietrzak', 'Wrocław', 'Wspieram małą fundację w zbieraniu opinii po warsztatach. Chcę testować krótką anonimową ankietę.', 'Tablet do ankiet'],
      ['Tymon Borkowski', 'Łódź', 'Organizuję dostawy rzeczy do punktu pomocy. Sprawdzę aktualizowanie potrzeb i uniknięcie wielokrotnego przywozu tego samego.', 'Samochód dostawczy po uzgodnieniu'],
      ['Klara Szymczak', 'Gdynia', 'Prowadzę grupę wolontariuszy z różnym doświadczeniem. Ocenię podział zadania na jasne, możliwe do przejęcia kroki.', 'Tablica warsztatowa'],
      ['Nikodem Maj', 'Poznań', 'Pomagam prowadzić społeczną wypożyczalnię narzędzi. Chętnie przetestuję protokół wydania i przypomnienia o zwrocie.', 'Zestaw narzędzi ręcznych'],
      ['Lara Wójcik', 'Lublin', 'Przygotowuję dostępne ogłoszenia dla osiedla. Sprawdzę publikowanie jednego komunikatu w formie tekstowej i do druku.', 'Drukarka laserowa'],
      ['Maksymilian Jaworski', 'Rzeszów', 'Pomagam przy wydarzeniach charytatywnych. Ocenię prosty panel zadań dla osób dołączających tylko na kilka godzin.', 'Radiotelefony'],
      ['Nadia Czarnecka', 'Opole', 'Prowadzę sąsiedzką wymianę umiejętności. Interesuje mnie dopasowanie krótkiej pomocy do wolnego czasu uczestników.', 'Sala spotkań po uzgodnieniu'],
      ['Miłosz Sadowski', 'Zielona Góra', 'Dokumentuję działania społeczne zdjęciami. Sprawdzę zbieranie informacji zwrotnej od uczestników po zakończonym wydarzeniu.', 'Aparat fotograficzny'],
    ],
  },
  {
    skills: ['Ocena informacji dla odbiorców', 'Animacja kultury'],
    resources: ['Smartfon'],
    accessibilityNeeds: '',
    interests: ['Kultura', 'Przestrzeń publiczna', 'Wspólne spędzanie czasu'],
    availability: 'hybrid',
    people: [
      ['Rozalia Kaczmarek', 'Toruń', 'Prowadzę spacery historyczne po osiedlu. Sprawdzę audioprzewodnik z krótkimi trasami i miejscami odpoczynku.', 'Dyktafon'],
      ['Gabriel Wojciechowski', 'Kalisz', 'Gram w amatorskim teatrze. Ocenię zapisy na warsztaty oraz informację o dostępności sali przed wizytą.', 'Laptop'],
      ['Łucja Lisowska', 'Sopot', 'Organizuję plenerowe czytanie książek. Chcę testować kalendarz małych wydarzeń z opcją przypomnienia o zmianie pogody.', 'Przenośny głośnik'],
      ['Władysław Kania', 'Zamość', 'Zbieram lokalne opowieści mieszkańców. Sprawdzę nagrywanie krótkiej historii i poprawianie jej tekstowego zapisu.', 'Rejestrator audio'],
      ['Otylia Wrona', 'Płock', 'Pomagam przy wystawach w małej galerii. Ocenię opisy prac w prostym języku i nawigację pomiędzy salami.', 'Tablet wystawowy'],
      ['Arkadiusz Przybylski', 'Bydgoszcz', 'Tworzę mapę miejsc bezpłatnego wypoczynku. Mogę sprawdzić filtrowanie po toaletach, ławkach i dojeździe.', 'Aparat z GPS'],
      ['Diana Wesołowska', 'Przemyśl', 'Śpiewam w międzypokoleniowym chórze. Ocenię udostępnianie materiałów do samodzielnego ćwiczenia przed próbą.', 'Słuchawki'],
      ['Juliusz Baranowski', 'Leszno', 'Prowadzę klub planszówek. Interesuje mnie dobór spotkań według długości gry i potrzeb początkujących.', 'Biblioteczka gier planszowych'],
      ['Celestyna Adamczyk', 'Słupsk', 'Pracuję społecznie przy małym kinie. Sprawdzę informacje o napisach, audiodeskrypcji i dostępności seansu.', 'Laptop z projektorem'],
      ['Jędrzej Makowski', 'Kłodzko', 'Pomagam odnawiać osiedlowy skwer. Ocenię konsultacje społeczne umożliwiające ocenę kilku wariantów zagospodarowania.', 'Miarka i aparat'],
    ],
  },
  {
    skills: ['Prototypowanie', 'Naprawy i pomiary'],
    resources: ['Podstawowe narzędzia ręczne'],
    accessibilityNeeds: '',
    interests: ['Obieg zamknięty', 'Czujniki', 'Technologie wspomagające'],
    availability: 'onsite',
    people: [
      ['Ada Zielonka', 'Gliwice', 'Drukuję drobne elementy z tworzywa. Sprawdzę obudowę czujnika i wygodę wymiany baterii bez dodatkowych narzędzi.', 'Drukarka 3D FDM'],
      ['Beniamin Cebula', 'Warszawa', 'Naprawiam lampki i małą elektronikę. Mogę ocenić czytelność oznaczeń oraz łatwość rozłożenia prototypu.', 'Multimetr i lutownica'],
      ['Celina Dębska', 'Wrocław', 'Szyję torby i organizery. Chętnie przetestuję uchwyt urządzenia dopasowany do wózka lub roweru.', 'Maszyna do szycia'],
      ['Dionizy Gajewski', 'Poznań', 'Pracuję hobbystycznie w drewnie. Ocenię stabilność prostych pomocy do codziennych czynności.', 'Mały warsztat stolarski'],
      ['Eliza Ostrowska', 'Kraków', 'Buduję dostępne kontrolery do gier. Sprawdzę duże przyciski i alternatywne sposoby podłączenia do komputera.', 'Mikrokontrolery i przyciski arkadowe'],
      ['Feliks Jabłoński', 'Łódź', 'Prowadzę sąsiedzkie naprawy rowerów. Chcę testować system opisu usterki i dobierania dostępnych części.', 'Stojak serwisowy do roweru'],
      ['Gaja Dudzińska', 'Lublin', 'Projektuję elementy do wycinania laserowego. Ocenię instrukcję składania prostego prototypu bez kleju.', 'Dostęp do pracowni laserowej po uzgodnieniu'],
      ['Hipolit Marciniak', 'Opole', 'Zbieram i naprawiam starsze radia. Sprawdzę obwód sygnalizacji i pomiary poboru prądu nowego urządzenia.', 'Oscyloskop'],
      ['Inga Sawicka', 'Gdańsk', 'Składam zestawy pomiarowe dla ogrodów. Interesuje mnie trwałość kabli oraz mocowanie czujników w deszczu.', 'Raspberry Pi'],
      ['Jeremi Zalewski', 'Tarnów', 'Projektuję proste uchwyty w programie CAD. Mogę sprawdzić ergonomię pokrętła i dopasować jego wymiary.', 'Suwmiarka i komputer z CAD'],
    ],
  },
  {
    skills: ['Ocena obciążenia interfejsu', 'Opis doświadczeń użytkownika'],
    resources: ['Laptop i smartfon'],
    accessibilityNeeds: 'Potrzebuję spokojnego otoczenia, możliwości wyłączenia animacji oraz przerw bez utraty postępu.',
    interests: ['Komfort sensoryczny', 'Spokojne interfejsy', 'Samodzielna organizacja'],
    availability: 'remote',
    people: [
      ['Jagna Wolska', 'Warszawa', 'Łatwo przeciążają mnie migające elementy i wiele powiadomień. Sprawdzę tryb skupienia w aplikacji do planowania dnia.', 'Słuchawki wyciszające'],
      ['Kajetan Rogowski', 'Kraków', 'Preferuję przewidywalną strukturę spotkania. Ocenię instrukcje przygotowania do wizyty w nowym miejscu.', 'Tablet'],
      ['Liwia Musiał', 'Poznań', 'Długie bloki tekstu utrudniają mi wykonanie zadania. Mogę testować podział formularza na krótkie etapy.', 'Czytnik tekstu na głos'],
      ['Maurycy Krawczyk', 'Wrocław', 'Pracuję najlepiej przy ograniczonej liczbie bodźców. Sprawdzę, czy istotne alerty dają się odróżnić od pozostałych.', 'Monitor z filtrem światła'],
      ['Noemi Urban', 'Łódź', 'Korzystam z list kontrolnych przy codziennych sprawach. Chcę testować wznawianie zadań po dłuższej przerwie.', 'Zegar wizualny'],
      ['Olaf Błaszczyk', 'Gdynia', 'Źle znoszę automatycznie odtwarzany dźwięk. Ocenię kontrolę multimediów i wyciszanie komunikatów w prototypie.', 'Słuchawki przewodowe'],
      ['Pola Wierzbicka', 'Lublin', 'Potrzebuję więcej czasu na przeczytanie polecenia. Sprawdzę formularze bez odliczania i z możliwością cofnięcia kroku.', 'Tablet z rysikiem'],
      ['Roch Jasiński', 'Rzeszów', 'Wolę kontakt pisemny niż niespodziewane rozmowy. Interesuje mnie umawianie testu z jasną agendą i czasem trwania.', 'Laptop Linux'],
      ['Salomea Kurek', 'Olsztyn', 'Przy hałasie trudno mi zebrać myśli. Mogę ocenić mapę spokojnych miejsc do pracy i odpoczynku.', 'Miernik hałasu w telefonie'],
      ['Tobiasz Witek', 'Białystok', 'Korzystam z przypomnień rozłożonych na małe kroki. Sprawdzę planowanie, w którym można odłożyć zadanie bez presji.', 'Smartwatch'],
    ],
  },
  {
    skills: ['Ocena zrozumiałości informacji', 'Komunikacja międzykulturowa'],
    resources: ['Laptop i smartfon'],
    accessibilityNeeds: '',
    interests: ['Integracja', 'Prosty język', 'Dostęp do informacji'],
    availability: 'remote',
    people: [
      ['Tamara Kowal', 'Lublin', 'Pomagam w polsko-ukraińskich spotkaniach sąsiedzkich. Ocenię instrukcję zapisu do biblioteki w obu językach.', 'Klawiatura polska i ukraińska'],
      ['Leonard Kaczmarczyk', 'Warszawa', 'Posługuję się polskim i angielskim w codziennej pracy. Sprawdzę spójność tłumaczeń formularza zgłoszeniowego.', 'Laptop Windows'],
      ['Mira Domańska', 'Gdańsk', 'Redaguję informacje dla nowych mieszkańców. Chętnie ocenię objaśnienia skrótów i nazw polskich instytucji.', 'Edytor tekstu'],
      ['Samuel Głowacki', 'Wrocław', 'Znam polski i niemiecki. Mogę porównać komunikaty o transporcie oraz upewnić się, że daty i godziny są zrozumiałe.', 'Telefon z dwoma językami systemu'],
      ['Nela Król', 'Poznań', 'Prowadzę konwersacje po polsku dla dorosłych. Sprawdzę poziom trudności krótkich komunikatów w aplikacji.', 'Mikrofon do rozmów online'],
      ['Bruno Jakubowski', 'Kraków', 'Tłumaczę hobbystycznie teksty z hiszpańskiego. Ocenię instrukcje korzystania z lokalnych wydarzeń bez znajomości miasta.', 'Tablet'],
      ['Marlena Sokołowska', 'Łódź', 'Pomagam przy spotkaniach polsko-białoruskich. Sprawdzę wyszukiwanie informacji bez konieczności znajomości urzędowego terminu.', 'Laptop z układem cyrylicy'],
      ['Seweryn Walczak', 'Katowice', 'Używam polskiego i czeskiego. Interesują mnie proste objaśnienia zasad zapisów oraz anulowania udziału w wydarzeniu.', 'Telefon Android'],
      ['Aurelia Cichocka', 'Szczecin', 'Redaguję teksty łatwe do czytania. Mogę porównać ikonę, opis i rzeczywisty skutek naciśnięcia przycisku.', 'Monitor 24 cale'],
      ['Kornel Majewski', 'Rzeszów', 'Prowadzę wielojęzyczne quizy integracyjne. Ocenię wybór języka oraz zachowanie polskich znaków w formularzach.', 'Projektor'],
    ],
  },
  {
    skills: ['Planowanie aktywności', 'Ocena sprzętu w użyciu'],
    resources: ['Telefon z GPS'],
    accessibilityNeeds: '',
    interests: ['Aktywność fizyczna', 'Integracja przez sport', 'Rekreacja'],
    availability: 'onsite',
    people: [
      ['Ludwika Wawrzyniak', 'Gdańsk', 'Organizuję spokojne marsze dla początkujących. Ocenię trasy z informacją o nawierzchni, ławkach i toaletach.', 'Kijki do nordic walking'],
      ['Aleksy Rutkowski', 'Kraków', 'Jeżdżę na rowerze z grupą osób o różnym tempie. Sprawdzę aplikację, która pomaga nikogo nie zostawić w tyle.', 'Rower i licznik GPS'],
      ['Rita Gajda', 'Wrocław', 'Prowadzę ćwiczenia rozciągające w parku. Interesuje mnie system zapisów uwzględniający różne poziomy doświadczenia.', 'Maty treningowe'],
      ['Wawrzyniec Stępień', 'Poznań', 'Biegam rekreacyjnie i testuję trasy poza głównymi ulicami. Ocenię czytelność mapy oraz instrukcji głosowych.', 'Zegarek sportowy'],
      ['Matylda Kłos', 'Łódź', 'Uczę dorosłych jazdy na rowerze. Sprawdzę krótkie filmy instruktażowe i kalendarz dostępnych zajęć.', 'Rower miejski'],
      ['Dymitr Szczepański', 'Katowice', 'Pomagam przy turniejach bocci. Chcę testować zapisy drużyn i dostępne opisy zasad dla nowych uczestników.', 'Zestaw do bocci'],
      ['Hanna Kołodziej', 'Lublin', 'Organizuję spacery z psami ze schroniska. Ocenię dobieranie trasy do możliwości uczestnika i czasu wyjścia.', 'Smycze spacerowe'],
      ['Leopold Sowa', 'Bielsko-Biała', 'Chodzę po łatwych szlakach i dokumentuję miejsca odpoczynku. Sprawdzę opis przewyższeń bez specjalistycznych map.', 'Odbiornik GPS'],
      ['Wera Bąk', 'Olsztyn', 'Pływam rekreacyjnie i korzystam z kilku basenów. Ocenię informacje o godzinach spokojnego pływania i dostępności szatni.', 'Opaska sportowa'],
      ['Apolinary Duda', 'Zielona Góra', 'Koordynuję otwarte zajęcia tenisa stołowego. Sprawdzę rezerwację stołu i znalezienie partnera o podobnym poziomie.', 'Zestaw rakietek'],
    ],
  },
  {
    skills: ['Planowanie zasobów', 'Praktyczne testy w gospodarstwie domowym'],
    resources: ['Smartfon'],
    accessibilityNeeds: '',
    interests: ['Ograniczanie marnowania żywności', 'Ogrody społeczne', 'Współdzielenie'],
    availability: 'hybrid',
    people: [
      ['Melania Jankowska', 'Kraków', 'Przygotowuję posiłki na kilka dni i zapisuję terminy produktów. Sprawdzę przypomnienia ograniczające wyrzucanie jedzenia.', 'Waga kuchenna'],
      ['Barnaba Krajewski', 'Warszawa', 'Opiekuję się kompostownikiem osiedlowym. Ocenię czujnik temperatury i instrukcję prowadzenia kompostu.', 'Kompostownik społeczny'],
      ['Blanka Mazur', 'Wrocław', 'Uprawiam zioła na balkonie. Chcę testować prosty system podlewania z informacją o pustym zbiorniku.', 'Donice balkonowe'],
      ['Cyprian Wilk', 'Poznań', 'Pomagam w odbiorze nadwyżek z piekarni. Sprawdzę ogłoszenia z krótkim terminem odbioru i aktualną liczbą porcji.', 'Torby termiczne'],
      ['Dobrawa Kalinowska', 'Gdańsk', 'Wspólnie z sąsiadami prowadzę grządki warzywne. Ocenię kalendarz podlewania i zgłaszanie dostępnych plonów.', 'Grządka społeczna'],
      ['Florian Wróbel', 'Łódź', 'Przeliczam przepisy na różną liczbę osób. Interesuje mnie czytelna lista zakupów dopasowana do tego, co już mam.', 'Tablet kuchenny'],
      ['Gizela Bielecka', 'Toruń', 'Organizuję wymianę sadzonek i nasion. Sprawdzę etykiety roślin i rezerwowanie odbioru w dogodnym terminie.', 'Mała szklarnia'],
      ['Hieronim Jaworski', 'Kielce', 'Doglądam ogrodu w okresach suszy. Mogę porównywać wskazania czujnika wilgotności z ręczną oceną gleby.', 'System podlewania kropelkowego'],
      ['Ida Wysocka', 'Opole', 'Wspieram jadłodzielnię przy bibliotece. Ocenię komunikaty o świeżych dostawach i prostą listę potrzeb.', 'Termometr lodówkowy'],
      ['Ksawery Kurek', 'Szczecin', 'Przygotowuję przetwory i pilnuję dat w spiżarni. Chcę testować skanowanie etykiet oraz wyszukiwanie produktów.', 'Drukarka etykiet'],
    ],
  },
  {
    skills: ['Organizacja pracy', 'Ocena procesów'],
    resources: ['Laptop'],
    accessibilityNeeds: '',
    interests: ['Włączenie zawodowe', 'Uczenie nowych umiejętności', 'Współpraca'],
    availability: 'hybrid',
    people: [
      ['Berenika Szymkowiak', 'Warszawa', 'Wracam do pracy po przerwie opiekuńczej. Sprawdzę plan nauki nowych narzędzi rozłożony na krótkie codzienne zadania.', 'Telefon iOS'],
      ['Ambroży Kaczor', 'Kraków', 'Prowadzę mały punkt usługowy. Ocenię grafik zmian oraz proste zastępstwa bez rozbudowanego systemu kadrowego.', 'Tablet przy stanowisku pracy'],
      ['Cecylia Nowakowska', 'Poznań', 'Pomagam osobom zmieniającym zawód opisywać doświadczenie. Sprawdzę kreator portfolio napisany prostym językiem.', 'Kamera do rozmów online'],
      ['Emanuel Ostrowski', 'Wrocław', 'Pracuję zdalnie w kilku projektach społecznych. Interesują mnie jasne priorytety i możliwość wyłączenia zbędnych alertów.', 'Dwa monitory'],
      ['Estera Piotrowska', 'Łódź', 'Wdrażam nowe osoby w spółdzielni. Ocenię instrukcje stanowiskowe z fotografiami i możliwością potwierdzenia kroku.', 'Telefon z aparatem'],
      ['Gerard Michalak', 'Gdańsk', 'Pracuję na zmiany i uczę się wieczorami. Sprawdzę elastyczny kalendarz zajęć dostępnych w różnych godzinach.', 'Słuchawki z mikrofonem'],
      ['Jowita Zawadzka', 'Lublin', 'Szukam pierwszej pracy po ukończeniu szkoły. Mogę ocenić zrozumiałość ogłoszeń oraz formularza zgłoszenia.', 'Chromebook'],
      ['Lucjan Sobczak', 'Katowice', 'Prowadzę naprawy domowe na niewielką skalę. Chcę testować łączenie krótkich zleceń sąsiedzkich z wolnymi terminami.', 'Zestaw narzędzi'],
      ['Mirella Pawłowska', 'Rzeszów', 'Koordynuję pracę zespołu osób w różnym wieku. Ocenię przekazywanie zmian bez długich wątków wiadomości.', 'Współdzielona tablica zadań'],
      ['Wincenty Grabowski', 'Białystok', 'Uczę się obsługi narzędzi biurowych po zmianie branży. Sprawdzę instrukcje eksportu dokumentów i bezpiecznego zapisu pracy.', 'Laptop z pakietem biurowym'],
    ],
  },
];

export const testerSeedProfiles: TesterProfileInput[] = [
  ...profiles,
  ...groups.flatMap(({ people, ...shared }) =>
    people.map(([displayName, city, bio, resource]) => ({
      ...shared,
      displayName,
      city,
      bio,
      resources: [...shared.resources, resource],
    })),
  ),
].map(
  (profile) =>
    TesterProfileInputSchema.parse({
      ...profile,
    }),
);
